name: Cypress Tests

on:
  push:
    branches:
      - staging
  # schedule:
  #   # Runs every 5 minutes
  #   - cron: "*/5 * * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    # environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: staging

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress E2E run
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress/config/cypress.config.ts
          config: baseUrl=http://localhost:3000
          # record: true
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # cypress e2e env vars
          TEST_ENV: ${{ vars.TEST_ENV }}

      # Upload screenshots on failure
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30

      # # Upload videos
      # - name: Upload videos
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
      #     retention-days: 30

      # Upload tests reports
      - name: Upload html reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-tests-html-reports
          path: cypress/reports/html
          retention-days: 30

      # Deploy tests reports to github pages
      - name: Deploy tests reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports
